name: CI-FrontEnd

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      EC2_URL: ${{ secrets.EC2_URL }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}

    steps:
      - uses: actions/checkout@v4
      - name: Build and Publish head Docker image
        uses: VaultVulp/gp-docker-action@1.0.1
        with:
          github-token: ${{ secrets.GIT_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: front-image # Provide Docker image name
          image-tag: latest
      - name: SSH to EC2
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > primerkey.pem
          chmod 400 "primerkey.pem"
      - name: Deploy to EC2
        run: |
          ssh -i "primerkey.pem" -o StrictHostKeyChecking=no -t $EC2_USERNAME@$EC2_URL << 'EOF'
            echo "Conectado a EC2"
            docker login ghcr.io -u ${{ secrets.GIT_USER }} -p ${{ secrets.GIT_TOKEN }}
            docker pull ghcr.io/${{ secrets.GIT_USER }}/front-image:latest
            docker stop front-container || true
            docker run -p 80:80 front-container      
          EOF
